### ISSUE TITLE
What WAI is Working On - Page Title?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-about-wai#127]
See Requirements Analysis, **particularly [User Scenarios.](https://github.com/w3c/wai-about-wai/wiki/What-WAI-is-Working-On-Requirements-Analysis#user-scenarios)**

What might we want to title this page? Think from the user perspective...

**All brainstorms welcome!** _&mdash; including ideas you don't really like, and list here to help generate ideas from others :-)_

**Comment by bakkenb** [comment]
- WAI Roadmap
- What's Coming Next
- Next Up for WAI
- Current and Future Work
- Current and Future Resources
- What We are Working on [Now]
- Join Our Work, Here is What We Are Doing Now

**Comment by jade-mc** [comment]
The WAI forward

Done.

**Comment by mpalmersg** [comment]
WAI2GO

**Comment by iadawn** [comment]
- Accessibility work at W3C
- Get involved with accessibility at W3C

**Comment by iadawn** [comment]
* A11y@W3C

**Comment by shawna-slh** [comment]
I updated the requirements analysis to clarify scope is likely all accessibility work at W3C:
> Generally, all accessibility-related work at W3C, including things not directly under "WAI umbrella" like EPUB accessibility and timed text.

**Comment by shawna-slh** [comment]
from @brewerj
> I think your original title, what's wai up to, better captures the spirit of the update. The current title, Accessibility Work at W3C, sounds more like a static web page. If I were somewhat familiar with WAI, I'd probably skip reading it, not realizing that it's the latest.

**Comment by shawna-slh** [comment]
Reminders:
* **[goals, scenarios, etc](https://github.com/w3c/wai-about-wai/wiki/What-WAI-is-Working-On-Requirements-Analysis#purposegoalsobjectives)**
* scope is mostly WAI yet also includes W3C accessibility work not directly under WAI organizationally

Here's the latest **[nearly-done first iteration](https://deploy-preview-126--wai-about-wai.netlify.app/about/new-work/)**

brainstorm:
<img src="https://user-images.githubusercontent.com/6991814/157792521-b224e61e-ce22-4733-889a-ae2ef5a08644.png" width="357">
image description: "Accessibility Work at W3C" big, with under it, smaller, italics "What we're up to in March 2022"

Obviously putting the month means it needs to be updated monthly. Yet, that's pretty easy (and I'd be the one doing it most of the time :-) and probably worth it to be clear up front that it is indeed current.

**Comment by shawna-slh** [comment]
more brainstorming:
* Advancing Accessibility at W3C<br>_March 2020 Current Work at WAI and Beyond_
* What We're Working on at W3C WAI<br>_March 2020 Accessibility Activities_
* Current Accessibility Work at W3C
* ...

**Comment by brewerj** [comment]
"WAI2GO" from @mpalmersg above seems fun and easy to remember, maybe better than the original "What's WAI up to." 

"What We're Working on at W3C WAI" from @shawna-slh is probably the clearest.

**Comment by shawna-slh** [comment]
[EOWG minutes 11 March 2022](https://www.w3.org/2022/03/11-eo-minutes.html#item02)
