### ISSUE TITLE
Comments on Requirements Analysis for What WAI is Working On

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-about-wai#128]
What might we want to add, delete, or change in the [Requirements Analysis for _What WAI is Working On_](https://github.com/w3c/wai-about-wai/wiki/What-WAI-is-Working-On-Requirements-Analysis#what-wai-is-working-on--requirements-analysis)?

(Please put comments on the page title in separate [Issue 127](https://github.com/w3c/wai-about-wai/issues/127).)

_**Note:** the Requirements Analysis is an internal document so we do **not** want to spend effort wordsmithing or polishing, or including every possible detail._

**Comment by bakkenb** [comment]
Upon first reading this requirements analysis I was thinking this was about what EOWG is working on. Then when I got to the bottom I realized this was for all of WAI work. Maybe need to be more clear that this would/could cover work from all WAI working groups not just what is being worked on by EOWG.

**Comment by bakkenb** [comment]
User Scenario - I work as an accessibility specialist in a large company. I would like to know what specifications and additional resources are being created so I can follow that work and share them with my colleagues when the are published.

**Comment by shawna-slh** [comment]
Thanks, Brent, I'm adding both above to the doc.
