### ISSUE TITLE
Accessibility Work at W3C

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-about-wai#129]
Comment below on [[DRAFT] Accessibility Work at W3C](https://deploy-preview-126--wai-about-wai.netlify.app/about/new-work/)

Or, start a new issue with Assignee @shawna-slh

**Comment by karenmyers** [comment]
I like the persona statements to help people identify their needs. Can we provide a short summary statement of what each working group is focused on achieving?  Any chance we can add some visuals to the document?Finally, if there were a "next six months" expected milestones, or actions to for members and non-members that would be great.

**Comment by shawna-slh** [comment]
Thanks for the input, Karen!

> Can we provide a short summary statement of what each working group is focused on achieving?

Those happen to be at the top of https://www.w3.org/groups/wg/ and under "[Participating in Working Groups](https://www.w3.org/groups/wg/)"

I'd rather not clutter this new page with them here, too.

I did add [links to each Working Group's current work](https://deploy-preview-126--wai-about-wai.netlify.app/about/new-work/#wait-wait-theres-more). (Now I just need to get those links :-)

> Any chance we can add some visuals to the document?

I hope to fancy it up at some point. Right now I'm pulling teeth just to get basic info in there.

> Finally, if there were a "next six months" expected milestones, or actions to for members and non-members that would be great.

Added section on [upcoming publications](https://deploy-preview-126--wai-about-wai.netlify.app/about/new-work/#coming-soon-to-a-publication-near-you). I hope people will help fill it in by Friday!

**Comment by karenmyers** [comment]
Hi Shawn,

Sorry for late reply today after you were working late last night.

This is coming along nicely!  Thank you for all the work you are doing and coordinating with everyone. Alan and I think it will help to provide clear and up-to-date messaging for next week.

Karen
