### ISSUE TITLE
[Translating review] Typo?

### ISSUE THREAD

**Issue by notabene** [w3c/wai-about-wai#32]
Reviewing https://w3c.github.io/wai-about-wai/about/translating/

> Qualifying accessibility/disability or translation organizations

I suppose there is a typo as I can't figure out what this means as it is now; in paragraph “Links to organizations. (Exception: Qualifying accessibility/disability or translation organizations. To request an exception, e-mail wai@w3.org with subject [Translations link request].)”.

**Comment by slhenry** [comment]
Thanks for the input. It is trying to say this in less words:
Qualifying accessibility organizations, disability organizations, or translation organizations.

Does this work?
> Qualifying accessibility/disability organizations, or translation organizations.

**Comment by notabene** [comment]
Ah I get it now :)

> Qualifying accessibility/disability organizations or translation organizations.

This works better, yes, thank you!

**Comment by slhenry** [comment]
https://github.com/w3c/wai-about-wai/commit/4815ce35a65323ba69d54a1deda95654de25bcc7#diff-f58cd2e6d828bbc727991bd2e19b77f2
