### ISSUE TITLE
[typo/bug] WAI-Tools page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-about-wai#33]
https://www.w3.org/WAI/about/projects/wai-tools/

> D3.1: Accessibility Statement Generator — open source tool, possibly extending the WCAG-EM Report Tool , to assist the creation of accessibility statements.

WCAG-EM Report Tool -> https://www.w3.org/WAI/planning/statements/generator/#create

**Comment by nitedog** [comment]
fixed, thanks
