### ISSUE TITLE
“thanks these translators”

### ISSUE THREAD

**Issue by notabene** [w3c/wai-about-wai#35]
Small question:
« WAI remercie ces traducteurs, » implies we have several translators for the present document, yet most documents are translated by one person. In French it sounds a bit awkward. (And I'm guessing it's the same in most languages.)

What about saying: “WAI thanks translators” which would be translated then to « WAI remercie les traducteurs »?

**Comment by slhenry** [comment]
Great! [Done.](https://github.com/w3c/wai-website-data/commit/f642fd1a98cd884958bc2fca703fdc412d264833#diff-9d31a970248a8964164d48b618b6060b)
