### ISSUE TITLE
Broken link on "WAI Working Groups and Interest Groups" page

### ISSUE THREAD

**Issue by brennanyoung** [w3c/wai-about-wai#4]
The link to the ARIA group https://www.w3.org/WAI/about/groups/aria/ is a 404. 

Does the group still exist?

**Comment by yatil** [comment]
@brennanyoung The correct link is https://www.w3.org/WAI/about/groups/ariawg/ – I also added a redirect from the URL you quoted above.

Can you tell us where you found the link above?

**Comment by brennanyoung** [comment]
@yatil the link was from https://www.w3.org/WAI/about/groups/

**Comment by yatil** [comment]
@brennanyoung thanks, I made some more fixes to that page :-)
