### ISSUE TITLE
[Translating WAI Resources] link to "WCAG 2 Translations"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-about-wai#55]
Link to: https://www.w3.org/WAI/standards-guidelines/wcag/translations/
From: https://www.w3.org/WAI/about/translating/
Rationale: make it easier to find

**Comment by slhenry** [comment]
That link is on that page, under [High priority WCAG resources](https://www.w3.org/WAI/about/translating/#priority-wcag):
> * [WCAG 2 Translations][https://www.w3.org/WAI/standards-guidelines/wcag/translations/] lists translations in-progress and completed.

Also, at the top of [Translating WAI Resources][https://www.w3.org/WAI/about/translating/], the second sentence says:
> For a list of existing translations, see [All WAI Translations](https://www.w3.org/WAI/translations/).

That pages includes all completed translations of WCAG 2.

---

I think those meet most use cases.

**Comment by nitedog** [comment]
Here my journey:

1. I want to see which authorized translations exist
2. I find "All translations" at the top of the page - yay!
3. I first only see the individual languages - hmmm
4. Then I find "Translating WAI Resources" - yay!
5. There I find "TR & Authorized Translations" - yay!
6. Dead-end. Where is that page, I know it exists?!

Maybe this is a unique experience and all people know to go to "Standards/Guidelines -> WCAG -> Translations" rather than through "All Translations" but maybe not.

Actually, I change my suggestion to linking it directly from "All WAI Translations".

**Comment by slhenry** [comment]
I mildly think it might be more confusing for most readers. Yet, since it's at the bottom of both pages and given the wording, hopefully not.

Edit suggestions welcome.
